### PR TITLE
Patch 2 (Again)

### PR DESCRIPTION
**Pull request by junepark678**
Pls merge nebula, I wanna see Flowercat DIE!!!!

### CODE REVIEW

**Comment by stx3plus1** [comment]
why

**Comment by junepark678** [comment]
To destroy Flowercat when admins say yes

**Comment by stx3plus1** [comment]
pointless, flowercat >>> cosmo

**Comment by junepark678** [comment]
fr, that's the point. When nebula sees that flowercat fails when run a command, nebula will remove flowercat and replace it with cosmo

**Comment by stx3plus1** [comment]
NO

**Comment by junepark678** [comment]
COSMO ON TOP say goodbye

**Comment by Beast9265** [comment]
hi palera1n

**Comment by Beast9265** [comment]
eta beast unban

**Comment by plooshi** [comment]
rf

**Pull request closed without merging**
